import { Button, Dropdown, Field, Input, Option } from "@fluentui/react-components";
import { ArrowDownload20Regular, Play20Regular } from "@fluentui/react-icons";
import type { ReportFilterOptions, ReportFilters, ReportType } from "../../types/report";

interface Props { type: ReportType; value: ReportFilters; options: ReportFilterOptions; generating: boolean; onChange: React.Dispatch<React.SetStateAction<ReportFilters>>; onGenerate: () => void; onExport: () => void; }
const selectedLabel = (items: Array<{ value: string; label: string }>, value: string, fallback: string) => items.find((item) => item.value === value)?.label ?? fallback;

export function ReportFiltersPanel({ type, value, options, generating, onChange, onGenerate, onExport }: Props) {
  const set = <K extends keyof ReportFilters>(key: K, next: ReportFilters[K]) => onChange((current) => ({ ...current, [key]: next }));
  const periodApplicable = type === "operations" || type === "guarantees" || type === "documents";
  return <div className="report-filters">
    <div className="report-filters__fields">
      <Field label="Fazenda"><Dropdown value={selectedLabel(options.farms, value.farmId, "Todas as fazendas")} selectedOptions={[value.farmId]} onOptionSelect={(_, data) => set("farmId", data.optionValue ?? "")}><Option value="">Todas as fazendas</Option>{options.farms.map((farm) => <Option key={farm.value} value={farm.value}>{farm.label}</Option>)}</Dropdown></Field>
      <Field label="Situação"><Dropdown value={selectedLabel(options.statuses, value.status, "Todas")} selectedOptions={[value.status]} onOptionSelect={(_, data) => set("status", data.optionValue ?? "")}><Option value="">Todas</Option>{options.statuses.map((status) => <Option key={status.value} value={status.value}>{status.label}</Option>)}</Dropdown></Field>
      {type === "owners" ? <Field label="Tipo de pessoa"><Dropdown value={{ all: "Todos", individual: "Pessoa Física", company: "Pessoa Jurídica" }[value.ownerType]} selectedOptions={[value.ownerType]} onOptionSelect={(_, data) => set("ownerType", (data.optionValue ?? "all") as ReportFilters["ownerType"])}><Option value="all">Todos</Option><Option value="individual">Pessoa Física</Option><Option value="company">Pessoa Jurídica</Option></Dropdown></Field> : null}
      {type === "registrations" ? <Field label="HP"><Dropdown value={{ all: "Todos", yes: "Sim", no: "Não" }[value.hp]} selectedOptions={[value.hp]} onOptionSelect={(_, data) => set("hp", (data.optionValue ?? "all") as ReportFilters["hp"])}><Option value="all">Todos</Option><Option value="yes">Sim</Option><Option value="no">Não</Option></Dropdown></Field> : null}
      {type === "operations" || type === "guarantees" ? <Field label="Banco"><Dropdown value={value.bank || "Todos os bancos"} selectedOptions={[value.bank]} onOptionSelect={(_, data) => set("bank", data.optionValue ?? "")}><Option value="">Todos os bancos</Option>{options.banks.map((bank) => <Option key={bank} value={bank}>{bank}</Option>)}</Dropdown></Field> : null}
      {type === "guarantees" ? <Field label="Tipo de garantia"><Dropdown value={value.guaranteeType || "Todos os tipos"} selectedOptions={[value.guaranteeType]} onOptionSelect={(_, data) => set("guaranteeType", data.optionValue ?? "")}><Option value="">Todos os tipos</Option>{options.guaranteeTypes.map((item) => <Option key={item} value={item}>{item}</Option>)}</Dropdown></Field> : null}
      {type === "documents" ? <><Field label="Tipo de documento"><Dropdown value={value.documentType || "Todos os tipos"} selectedOptions={[value.documentType]} onOptionSelect={(_, data) => set("documentType", data.optionValue ?? "")}><Option value="">Todos os tipos</Option>{options.documentTypes.map((item) => <Option key={item} value={item}>{item}</Option>)}</Dropdown></Field><Field label="Vencimento"><Dropdown value={value.expirationWindow === "all" ? "Qualquer data" : `Próximos ${value.expirationWindow} dias`} selectedOptions={[value.expirationWindow]} onOptionSelect={(_, data) => set("expirationWindow", (data.optionValue ?? "all") as ReportFilters["expirationWindow"])}><Option value="all">Qualquer data</Option><Option value="30">Próximos 30 dias</Option><Option value="60">Próximos 60 dias</Option><Option value="90">Próximos 90 dias</Option></Dropdown></Field></> : null}
      {periodApplicable ? <><Field label="Período inicial"><Input type="date" value={value.startDate} onInput={(event) => set("startDate", event.currentTarget.value)} onChange={(_, data) => set("startDate", data.value)} /></Field><Field label="Período final"><Input type="date" value={value.endDate} onInput={(event) => set("endDate", event.currentTarget.value)} onChange={(_, data) => set("endDate", data.value)} /></Field></> : null}
    </div>
    <div className="report-filters__actions"><Button appearance="primary" icon={<Play20Regular />} disabled={generating} onClick={onGenerate}>{generating ? "Gerando..." : "Gerar relatório"}</Button><Button appearance="secondary" icon={<ArrowDownload20Regular />} onClick={onExport}>Exportar</Button></div>
  </div>;
}
