import { useEffect, useMemo, useState } from "react";
import { Button, Dialog, DialogActions, DialogBody, DialogContent, DialogSurface, DialogTitle, Dropdown, Field, Input, Option } from "@fluentui/react-components";
import type { DocumentAttachment } from "../../types/domain";
import type { AttachmentDraft } from "../../types/documento";

interface Props { open: boolean; value?: DocumentAttachment | AttachmentDraft; saving?: boolean; serviceError?: string; onClose: () => void; onSave: (draft: AttachmentDraft) => void; }

const storageLabels: Record<AttachmentDraft["storageType"], string> = { network_share: "Compartilhamento de rede", supabase_storage: "Supabase Storage", external: "Referência externa" };

export function AttachmentFormDialog({ open, value, saving = false, serviceError, onClose, onSave }: Props) {
  const [draft, setDraft] = useState({ fileName: "", filePath: "", storageType: "network_share" as AttachmentDraft["storageType"], fileType: "application/pdf", fileSizeKb: "" });
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => { if (!open) return; setDraft({ fileName: value?.fileName ?? "", filePath: value?.filePath ?? "", storageType: value?.storageType ?? "network_share", fileType: value?.fileType ?? "application/pdf", fileSizeKb: value?.fileSize === undefined ? "" : String(Math.round(value.fileSize / 1024)) }); setSubmitted(false); }, [open, value]);
  const errors = useMemo(() => ({ fileName: draft.fileName.trim() ? "" : "Informe o nome do arquivo.", filePath: draft.filePath.trim() ? "" : "Informe o caminho de rede do arquivo.", fileSize: draft.fileSizeKb && (!Number.isFinite(Number(draft.fileSizeKb)) || Number(draft.fileSizeKb) < 0) ? "Informe um tamanho válido." : "" }), [draft]);
  const submit = (event: React.FormEvent) => { event.preventDefault(); setSubmitted(true); if (Object.values(errors).some(Boolean)) return; onSave({ fileName: draft.fileName.trim(), filePath: draft.filePath.trim(), storageType: draft.storageType, fileType: draft.fileType.trim() || undefined, fileSize: draft.fileSizeKb ? Number(draft.fileSizeKb) * 1024 : undefined }); };
  return <Dialog open={open} onOpenChange={(_, data) => { if (!data.open && !saving) onClose(); }}><DialogSurface className="attachment-dialog"><DialogBody><DialogTitle>{value ? "Editar referência de arquivo" : "Adicionar referência de arquivo"}</DialogTitle><DialogContent><form id="attachment-form" className="attachment-form" onSubmit={submit} noValidate><p>Use esta opção para referências já existentes no servidor interno ou em fonte externa. Para armazenar um arquivo no Cloud, use “Enviar arquivo” no documento.</p><Field label="Nome do arquivo" required validationState={submitted && errors.fileName ? "error" : "none"} validationMessage={submitted ? errors.fileName : undefined}><Input autoFocus value={draft.fileName} placeholder="licenca_ambiental.pdf" onChange={(_, data) => setDraft((current) => ({ ...current, fileName: data.value }))} /></Field><Field label="Tipo de armazenamento" required><Dropdown value={storageLabels[draft.storageType]} selectedOptions={[draft.storageType]} onOptionSelect={(_, data) => setDraft((current) => ({ ...current, storageType: (data.optionValue ?? "network_share") as AttachmentDraft["storageType"] }))}><Option value="network_share">Compartilhamento de rede</Option><Option value="external">Referência externa</Option></Dropdown></Field><Field label="Caminho ou referência" required validationState={submitted && errors.filePath ? "error" : "none"} validationMessage={submitted ? errors.filePath : undefined}><Input value={draft.filePath} placeholder="\\ARQUIVOS\Imoveis\Fazenda\Documentos\arquivo.pdf" onChange={(_, data) => setDraft((current) => ({ ...current, filePath: data.value }))} /></Field><div className="attachment-form__row"><Field label="Tipo MIME"><Input value={draft.fileType} placeholder="application/pdf" onChange={(_, data) => setDraft((current) => ({ ...current, fileType: data.value }))} /></Field><Field label="Tamanho (KB)" validationState={submitted && errors.fileSize ? "error" : "none"} validationMessage={submitted ? errors.fileSize : undefined}><Input inputMode="numeric" value={draft.fileSizeKb} placeholder="Opcional" onChange={(_, data) => setDraft((current) => ({ ...current, fileSizeKb: data.value }))} /></Field></div>{serviceError ? <p className="registration-form__service-error" role="alert">{serviceError}</p> : null}</form></DialogContent><DialogActions><Button appearance="secondary" disabled={saving} onClick={onClose}>Cancelar</Button><Button appearance="primary" type="submit" form="attachment-form" disabled={saving}>{saving ? "Salvando..." : "Salvar referência"}</Button></DialogActions></DialogBody></DialogSurface></Dialog>;
}
