import { useEffect, useMemo, useState } from "react";
import { Button, Dialog, DialogActions, DialogBody, DialogContent, DialogSurface, DialogTitle, Field, Input } from "@fluentui/react-components";
import type { DocumentAttachment } from "../../types/domain";
import type { AttachmentDraft } from "../../types/documento";

interface Props { open: boolean; value?: DocumentAttachment | AttachmentDraft; saving?: boolean; serviceError?: string; onClose: () => void; onSave: (draft: AttachmentDraft) => void; }

export function AttachmentFormDialog({ open, value, saving = false, serviceError, onClose, onSave }: Props) {
  const [draft, setDraft] = useState({ fileName: "", filePath: "", fileType: "PDF", fileSizeKb: "" });
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => { if (!open) return; setDraft({ fileName: value?.fileName ?? "", filePath: value?.filePath ?? "", fileType: value?.fileType ?? "PDF", fileSizeKb: value?.fileSize === undefined ? "" : String(Math.round(value.fileSize / 1024)) }); setSubmitted(false); }, [open, value]);
  const errors = useMemo(() => ({ fileName: draft.fileName.trim() ? "" : "Informe o nome do arquivo.", filePath: draft.filePath.trim() ? "" : "Informe o caminho de rede do arquivo.", fileSize: draft.fileSizeKb && (!Number.isFinite(Number(draft.fileSizeKb)) || Number(draft.fileSizeKb) < 0) ? "Informe um tamanho válido." : "" }), [draft]);
  const submit = (event: React.FormEvent) => { event.preventDefault(); setSubmitted(true); if (Object.values(errors).some(Boolean)) return; onSave({ fileName: draft.fileName.trim(), filePath: draft.filePath.trim(), fileType: draft.fileType.trim() || undefined, fileSize: draft.fileSizeKb ? Number(draft.fileSizeKb) * 1024 : undefined }); };
  return <Dialog open={open} onOpenChange={(_, data) => { if (!data.open && !saving) onClose(); }}><DialogSurface className="attachment-dialog"><DialogBody><DialogTitle>{value ? "Editar referência de arquivo" : "Adicionar referência de arquivo"}</DialogTitle><DialogContent><form id="attachment-form" className="attachment-form" onSubmit={submit} noValidate><p>Registre apenas o caminho de rede. O protótipo não acessa nem altera arquivos físicos.</p><Field label="Nome do arquivo" required validationState={submitted && errors.fileName ? "error" : "none"} validationMessage={submitted ? errors.fileName : undefined}><Input autoFocus value={draft.fileName} placeholder="licenca_ambiental.pdf" onChange={(_, data) => setDraft((current) => ({ ...current, fileName: data.value }))} /></Field><Field label="Caminho de rede" required validationState={submitted && errors.filePath ? "error" : "none"} validationMessage={submitted ? errors.filePath : undefined}><Input value={draft.filePath} placeholder="\\ARQUIVOS\Imoveis\Fazenda\Documentos\arquivo.pdf" onChange={(_, data) => setDraft((current) => ({ ...current, filePath: data.value }))} /></Field><div className="attachment-form__row"><Field label="Tipo"><Input value={draft.fileType} placeholder="PDF" onChange={(_, data) => setDraft((current) => ({ ...current, fileType: data.value }))} /></Field><Field label="Tamanho (KB)" validationState={submitted && errors.fileSize ? "error" : "none"} validationMessage={submitted ? errors.fileSize : undefined}><Input inputMode="numeric" value={draft.fileSizeKb} placeholder="Opcional" onChange={(_, data) => setDraft((current) => ({ ...current, fileSizeKb: data.value }))} /></Field></div>{serviceError ? <p className="registration-form__service-error" role="alert">{serviceError}</p> : null}</form></DialogContent><DialogActions><Button appearance="secondary" disabled={saving} onClick={onClose}>Cancelar</Button><Button appearance="primary" type="submit" form="attachment-form" disabled={saving}>{saving ? "Salvando..." : "Salvar referência"}</Button></DialogActions></DialogBody></DialogSurface></Dialog>;
}

