import { useMemo } from "react";
import { Button, DataGrid, DataGridBody, DataGridCell, DataGridHeader, DataGridHeaderCell, DataGridRow, Menu, MenuItem, MenuList, MenuPopover, MenuTrigger, Skeleton, SkeletonItem, Tooltip, createTableColumn } from "@fluentui/react-components";
import type { TableColumnDefinition } from "@fluentui/react-components";
import { Add20Regular, Attach20Regular, ChevronLeft20Regular, ChevronRight20Regular, Delete20Regular, Edit20Regular, Eye20Regular, MoreHorizontal20Regular, PersonProhibited20Regular } from "@fluentui/react-icons";
import type { DocumentListItem } from "../../types/documento";
import { documentValidityLabels } from "../../services/statusLabels";
import { StatusBadge } from "../StatusBadge";

interface Props { records: DocumentListItem[]; loading: boolean; filtered: boolean; page: number; totalPages: number; onView: (record: DocumentListItem) => void; onEdit: (record: DocumentListItem) => void; onManageFiles: (record: DocumentListItem) => void; onInactivate: (record: DocumentListItem) => void; onDelete: (record: DocumentListItem) => void; onPageChange: (page: number) => void; onClear: () => void; onNew: () => void; }
const displayDate = (value?: string) => value ? new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${value.slice(0, 10)}T00:00:00Z`)) : "—";
const textCell = (value: string, strong = false) => <Tooltip content={value} relationship="description"><span className={`search-cell-text${strong ? " search-cell-text--strong" : ""}`}>{value}</span></Tooltip>;

export function DocumentGrid({ records, loading, filtered, page, totalPages, onView, onEdit, onManageFiles, onInactivate, onDelete, onPageChange, onClear, onNew }: Props) {
  const columns: TableColumnDefinition<DocumentListItem>[] = useMemo(() => [
    createTableColumn({ columnId: "type", compare: (a, b) => a.type.localeCompare(b.type, "pt-BR"), renderHeaderCell: () => "Tipo", renderCell: (item) => textCell(item.type, true) }),
    createTableColumn({ columnId: "number", compare: (a, b) => (a.number ?? "").localeCompare(b.number ?? ""), renderHeaderCell: () => "Número", renderCell: (item) => textCell(item.number || "—") }),
    createTableColumn({ columnId: "farm", compare: (a, b) => a.farmName.localeCompare(b.farmName, "pt-BR"), renderHeaderCell: () => "Fazenda", renderCell: (item) => textCell(item.farmName) }),
    createTableColumn({ columnId: "registration", compare: (a, b) => (a.registrationNumber ?? "").localeCompare(b.registrationNumber ?? ""), renderHeaderCell: () => "Matrícula", renderCell: (item) => item.registrationNumber || "Sem vínculo" }),
    createTableColumn({ columnId: "issue", compare: (a, b) => (a.issueDate ?? "").localeCompare(b.issueDate ?? ""), renderHeaderCell: () => "Emissão", renderCell: (item) => displayDate(item.issueDate) }),
    createTableColumn({ columnId: "expiration", compare: (a, b) => (a.expirationDate ?? "").localeCompare(b.expirationDate ?? ""), renderHeaderCell: () => "Validade", renderCell: (item) => displayDate(item.expirationDate) }),
    createTableColumn({ columnId: "status", compare: (a, b) => a.validityStatus.localeCompare(b.validityStatus), renderHeaderCell: () => "Situação", renderCell: (item) => <StatusBadge status={documentValidityLabels[item.validityStatus]} /> }),
    createTableColumn({ columnId: "files", compare: (a, b) => a.attachmentCount - b.attachmentCount, renderHeaderCell: () => "Arquivos", renderCell: (item) => <span className="document-file-count">{item.attachmentCount > 0 ? <Attach20Regular /> : null}{item.attachmentCount === 0 ? "Sem arquivo" : item.attachmentCount === 1 ? "1 arquivo" : `${item.attachmentCount} arquivos`}</span> }),
    createTableColumn({ columnId: "updated", compare: (a, b) => a.updatedAt.localeCompare(b.updatedAt), renderHeaderCell: () => "Atualizado em", renderCell: (item) => displayDate(item.updatedAt) }),
    createTableColumn({ columnId: "actions", renderHeaderCell: () => "Ações", renderCell: (item) => <div className="document-grid__actions" onClick={(event) => event.stopPropagation()}><Button appearance="subtle" size="small" icon={<Eye20Regular />} aria-label={`Visualizar ${item.type}`} onClick={() => onView(item)} /><Menu positioning="below-end"><MenuTrigger disableButtonEnhancement><Button appearance="subtle" size="small" icon={<MoreHorizontal20Regular />} aria-label={`Mais ações para ${item.type}`} /></MenuTrigger><MenuPopover><MenuList><MenuItem icon={<Eye20Regular />} onClick={() => onView(item)}>Visualizar</MenuItem><MenuItem icon={<Edit20Regular />} onClick={() => onEdit(item)}>Editar</MenuItem><MenuItem icon={<Attach20Regular />} onClick={() => onManageFiles(item)}>Gerenciar arquivos</MenuItem><MenuItem icon={<PersonProhibited20Regular />} disabled={item.status === "inactive"} onClick={() => onInactivate(item)}>Inativar</MenuItem><MenuItem className="registration-menu-danger" icon={<Delete20Regular />} onClick={() => onDelete(item)}>Excluir</MenuItem></MenuList></MenuPopover></Menu></div> }),
  ], [onDelete, onEdit, onInactivate, onManageFiles, onView]);
  if (loading) return <Skeleton className="search-results-skeleton" aria-label="Carregando documentos">{Array.from({ length: 10 }, (_, index) => <SkeletonItem key={index} shape="rectangle" size={40} />)}</Skeleton>;
  if (!records.length) return <div className="document-empty-state"><span><Attach20Regular /></span><h3>{filtered ? "Nenhum documento encontrado" : "Nenhum documento cadastrado"}</h3><p>{filtered ? "Ajuste os filtros para encontrar outros registros." : "Cadastre o primeiro documento rural do sistema."}</p><div>{filtered ? <Button onClick={onClear}>Limpar filtros</Button> : null}<Button appearance="primary" icon={<Add20Regular />} onClick={onNew}>Novo documento</Button></div></div>;
  return <><div className="data-grid-wrap document-grid"><DataGrid items={records} columns={columns} size="small" sortable getRowId={(item) => item.id}><DataGridHeader><DataGridRow>{({ renderHeaderCell, columnId }) => <DataGridHeaderCell className={`document-column--${String(columnId)}`}>{renderHeaderCell()}</DataGridHeaderCell>}</DataGridRow></DataGridHeader><DataGridBody<DocumentListItem>>{({ item, rowId }) => <DataGridRow<DocumentListItem> key={rowId} onClick={() => onView(item)}>{({ renderCell, columnId }) => <DataGridCell className={`document-column--${String(columnId)}`}>{renderCell(item)}</DataGridCell>}</DataGridRow>}</DataGridBody></DataGrid></div><nav className="consulta-pagination" aria-label="Paginação de documentos"><Button appearance="subtle" size="small" icon={<ChevronLeft20Regular />} disabled={page <= 1} onClick={() => onPageChange(page - 1)}>Anterior</Button><div className="consulta-pagination__pages">{Array.from({ length: totalPages }, (_, index) => index + 1).map((number) => <Button key={number} appearance={number === page ? "primary" : "subtle"} size="small" onClick={() => onPageChange(number)}>{number}</Button>)}</div><Button appearance="subtle" size="small" iconPosition="after" icon={<ChevronRight20Regular />} disabled={page >= totalPages} onClick={() => onPageChange(page + 1)}>Próxima</Button></nav></>;
}
