import { useEffect, useMemo, useState } from "react";
import { Button, Combobox, Drawer, DrawerBody, DrawerFooter, DrawerHeader, DrawerHeaderTitle, Dropdown, Field, Input, Option, Textarea } from "@fluentui/react-components";
import { Add20Regular, Delete20Regular, Dismiss24Regular, Save20Regular } from "@fluentui/react-icons";
import type { DocumentAttachment } from "../../types/domain";
import type { AttachmentDraft, DocumentDraft, DocumentListItem, DocumentOption } from "../../types/documento";
import { AttachmentFormDialog } from "./AttachmentFormDialog";

interface Props { open: boolean; document?: DocumentListItem; attachments?: DocumentAttachment[]; farms: DocumentOption[]; registrations: DocumentOption[]; types: string[]; saving: boolean; serviceError?: string; onClose: () => void; onSave: (draft: DocumentDraft, pendingAttachments: AttachmentDraft[]) => void; }
type State = { farmId: string; registrationId: string; type: string; number: string; exercise: string; issueDate: string; expirationDate: string; purpose: string; licensedArea: string; cab: string; sigamStatus: string; status: "active" | "inactive"; notes: string; };
const empty: State = { farmId: "", registrationId: "", type: "", number: "", exercise: "", issueDate: "", expirationDate: "", purpose: "", licensedArea: "", cab: "", sigamStatus: "", status: "active", notes: "" };
const numberValue = (value: string) => Number(value.replace(/\./g, "").replace(",", "."));

export function DocumentFormDrawer({ open, document, attachments = [], farms, registrations, types, saving, serviceError, onClose, onSave }: Props) {
  const [draft, setDraft] = useState<State>(empty);
  const [submitted, setSubmitted] = useState(false);
  const [farmQuery, setFarmQuery] = useState("");
  const [typeQuery, setTypeQuery] = useState("");
  const [pendingAttachments, setPendingAttachments] = useState<AttachmentDraft[]>([]);
  const [attachmentOpen, setAttachmentOpen] = useState(false);
  useEffect(() => { if (!open) return; const next = document ? { farmId: document.farmId, registrationId: document.registrationId ?? "", type: document.type, number: document.number ?? "", exercise: document.exercise ?? "", issueDate: document.issueDate ?? "", expirationDate: document.expirationDate ?? "", purpose: document.purpose ?? "", licensedArea: document.licensedArea === undefined ? "" : String(document.licensedArea).replace(".", ","), cab: document.cab ?? "", sigamStatus: document.sigamStatus ?? "", status: document.status, notes: document.notes ?? "" } : empty; setDraft(next); setFarmQuery(farms.find((farm) => farm.id === next.farmId)?.label ?? ""); setTypeQuery(next.type); setPendingAttachments([]); setSubmitted(false); }, [document, farms, open]);
  const availableRegistrations = registrations.filter((item) => item.farmId === draft.farmId);
  const filteredFarms = farms.filter((farm) => !farmQuery || farm.label.toLocaleLowerCase("pt-BR").includes(farmQuery.toLocaleLowerCase("pt-BR")) || farm.id === draft.farmId);
  const filteredTypes = types.filter((type) => !typeQuery || type.toLocaleLowerCase("pt-BR").includes(typeQuery.toLocaleLowerCase("pt-BR")) || type === draft.type);
  const errors = useMemo(() => ({ farmId: draft.farmId ? "" : "Selecione a fazenda vinculada.", type: draft.type.trim() ? "" : "Informe o tipo do documento.", dates: draft.issueDate && draft.expirationDate && draft.expirationDate < draft.issueDate ? "A data de validade não pode ser anterior à emissão." : "", area: draft.licensedArea && (!Number.isFinite(numberValue(draft.licensedArea)) || numberValue(draft.licensedArea) < 0) ? "A área licenciada não pode ser negativa." : "" }), [draft]);
  const submit = (event: React.FormEvent) => { event.preventDefault(); setSubmitted(true); if (Object.values(errors).some(Boolean)) return; onSave({ farmId: draft.farmId, registrationId: draft.registrationId || undefined, type: draft.type.trim(), number: draft.number.trim() || undefined, exercise: draft.exercise.trim() || undefined, issueDate: draft.issueDate || undefined, expirationDate: draft.expirationDate || undefined, purpose: draft.purpose.trim() || undefined, licensedArea: draft.licensedArea ? numberValue(draft.licensedArea) : undefined, cab: draft.cab.trim() || undefined, sigamStatus: draft.sigamStatus.trim() || undefined, status: draft.status, notes: draft.notes.trim() || undefined }, pendingAttachments); };
  const addPending = (attachment: AttachmentDraft) => { setPendingAttachments((current) => [...current, attachment]); setAttachmentOpen(false); };
  return <><Drawer className="search-result-drawer document-form-drawer" type="overlay" position="end" size="medium" open={open} onOpenChange={(_, data) => { if (!data.open && !saving) onClose(); }}><DrawerHeader><DrawerHeaderTitle action={<Button appearance="subtle" aria-label="Fechar formulário" icon={<Dismiss24Regular />} onClick={onClose} />}>{document ? "Editar documento" : "Novo documento"}</DrawerHeaderTitle></DrawerHeader><DrawerBody><form id="document-form" className="document-form" onSubmit={submit} noValidate><div className="document-form__intro"><strong>Dados do documento</strong><span>Cadastre a identificação, os vínculos e a validade</span></div><div className="document-form__grid">
    <Field className="document-form__wide" label="Fazenda" required validationState={submitted && errors.farmId ? "error" : "none"} validationMessage={submitted ? errors.farmId : undefined}><Combobox value={farmQuery} placeholder="Busque uma fazenda" onChange={(event) => { setFarmQuery(event.target.value); if (draft.farmId) setDraft((current) => ({ ...current, farmId: "", registrationId: "" })); }} onOptionSelect={(_, data) => { const id = data.optionValue ?? ""; setDraft((current) => ({ ...current, farmId: id, registrationId: "" })); setFarmQuery(farms.find((farm) => farm.id === id)?.label ?? ""); }}>{filteredFarms.map((farm) => <Option key={farm.id} value={farm.id}>{farm.label}</Option>)}</Combobox></Field>
    <Field label="Tipo do documento" required validationState={submitted && errors.type ? "error" : "none"} validationMessage={submitted ? errors.type : undefined}><Combobox freeform value={typeQuery} placeholder="Selecione ou informe" onChange={(event) => { setTypeQuery(event.target.value); setDraft((current) => ({ ...current, type: event.target.value })); }} onOptionSelect={(_, data) => { const type = data.optionText ?? ""; setDraft((current) => ({ ...current, type })); setTypeQuery(type); }}>{filteredTypes.map((type) => <Option key={type}>{type}</Option>)}</Combobox></Field>
    <Field label="Número"><Input value={draft.number} placeholder="Opcional" onChange={(_, data) => setDraft((current) => ({ ...current, number: data.value }))} /></Field>
    <Field label="Matrícula"><Dropdown disabled={!draft.farmId} value={availableRegistrations.find((item) => item.id === draft.registrationId)?.label ?? "Sem matrícula vinculada"} selectedOptions={[draft.registrationId]} onOptionSelect={(_, data) => setDraft((current) => ({ ...current, registrationId: data.optionValue ?? "" }))}><Option value="">Sem matrícula vinculada</Option>{availableRegistrations.map((item) => <Option key={item.id} value={item.id}>{item.label}</Option>)}</Dropdown></Field>
    <Field label="Exercício"><Input value={draft.exercise} placeholder="Ex.: 2026" onChange={(_, data) => setDraft((current) => ({ ...current, exercise: data.value }))} /></Field>
    <Field label="Data de emissão"><Input type="date" value={draft.issueDate} onInput={(event) => { const value = event.currentTarget.value; setDraft((current) => ({ ...current, issueDate: value })); }} onChange={(_, data) => setDraft((current) => ({ ...current, issueDate: data.value }))} /></Field>
    <Field label="Data de validade" validationState={submitted && errors.dates ? "error" : "none"} validationMessage={submitted ? errors.dates : undefined}><Input type="date" value={draft.expirationDate} onInput={(event) => { const value = event.currentTarget.value; setDraft((current) => ({ ...current, expirationDate: value })); }} onChange={(_, data) => setDraft((current) => ({ ...current, expirationDate: data.value }))} /></Field>
    <Field className="document-form__wide" label="Finalidade"><Textarea value={draft.purpose} placeholder="Descreva a finalidade do documento" onChange={(_, data) => setDraft((current) => ({ ...current, purpose: data.value }))} /></Field>
    <Field label="Área licenciada" validationState={submitted && errors.area ? "error" : "none"} validationMessage={submitted ? errors.area : undefined}><Input contentAfter="ha" value={draft.licensedArea} onChange={(_, data) => setDraft((current) => ({ ...current, licensedArea: data.value }))} /></Field>
    <Field label="CAB"><Input value={draft.cab} placeholder="Opcional" onChange={(_, data) => setDraft((current) => ({ ...current, cab: data.value }))} /></Field>
    <Field label="Situação SIGAM"><Input value={draft.sigamStatus} placeholder="Opcional" onChange={(_, data) => setDraft((current) => ({ ...current, sigamStatus: data.value }))} /></Field>
    <Field label="Situação cadastral"><Dropdown value={draft.status === "active" ? "Ativo" : "Inativo"} selectedOptions={[draft.status]} onOptionSelect={(_, data) => setDraft((current) => ({ ...current, status: (data.optionValue ?? "active") as State["status"] }))}><Option value="active">Ativo</Option><Option value="inactive">Inativo</Option></Dropdown></Field>
    <Field className="document-form__wide" label="Observações"><Textarea value={draft.notes} placeholder="Informações complementares" onChange={(_, data) => setDraft((current) => ({ ...current, notes: data.value }))} /></Field>
  </div><section className="document-form__attachments"><div><span><strong>Arquivos vinculados</strong><small>Referências de rede, sem upload ou acesso físico</small></span>{!document ? <Button appearance="secondary" size="small" icon={<Add20Regular />} onClick={() => setAttachmentOpen(true)}>Adicionar referência de arquivo</Button> : null}</div>{document ? <p>{attachments.length ? `${attachments.length} referência${attachments.length === 1 ? "" : "s"} vinculada${attachments.length === 1 ? "" : "s"}. Gerencie-as nos detalhes do documento.` : "Nenhuma referência de arquivo vinculada."}</p> : pendingAttachments.length ? <ul>{pendingAttachments.map((item, index) => <li key={`${item.filePath}-${index}`}><span><strong>{item.fileName}</strong><small>{item.filePath}</small></span><Button appearance="subtle" size="small" icon={<Delete20Regular />} aria-label={`Remover ${item.fileName}`} onClick={() => setPendingAttachments((current) => current.filter((_, currentIndex) => currentIndex !== index))} /></li>)}</ul> : <p>Nenhuma referência adicionada nesta etapa.</p>}</section>{serviceError ? <p className="registration-form__service-error" role="alert">{serviceError}</p> : null}</form></DrawerBody><DrawerFooter><Button appearance="primary" icon={<Save20Regular />} type="submit" form="document-form" disabled={saving}>{saving ? "Salvando..." : document ? "Salvar alterações" : "Salvar documento"}</Button><Button appearance="secondary" disabled={saving} onClick={onClose}>Cancelar</Button></DrawerFooter></Drawer><AttachmentFormDialog open={attachmentOpen} onClose={() => setAttachmentOpen(false)} onSave={addPending} /></>;
}

