import { Badge, Button, Drawer, DrawerBody, DrawerFooter, DrawerHeader, DrawerHeaderTitle, Menu, MenuItem, MenuList, MenuPopover, MenuTrigger } from "@fluentui/react-components";
import { Add20Regular, Copy20Regular, Delete20Regular, Dismiss24Regular, Edit20Regular, MoreHorizontal20Regular } from "@fluentui/react-icons";
import { formatArea } from "../../services/searchUtils";
import { documentValidityLabels } from "../../services/statusLabels";
import type { DocumentAttachment } from "../../types/domain";
import type { DocumentDetailsViewModel } from "../../types/documento";
import { StatusBadge } from "../StatusBadge";

interface Props { record?: DocumentDetailsViewModel; open: boolean; onClose: () => void; onEdit: () => void; onAddAttachment: () => void; onEditAttachment: (attachment: DocumentAttachment) => void; onCopyPath: (attachment: DocumentAttachment) => void; onRemoveAttachment: (attachment: DocumentAttachment) => void; }
const date = (value?: string) => value ? new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${value.slice(0, 10)}T00:00:00Z`)) : "—";
const size = (value?: number) => value === undefined ? "Tamanho não informado" : value >= 1048576 ? `${new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 1 }).format(value / 1048576)} MB` : `${Math.round(value / 1024)} KB`;

export function DocumentDetailsDrawer({ record, open, onClose, onEdit, onAddAttachment, onEditAttachment, onCopyPath, onRemoveAttachment }: Props) {
  const item = record?.document;
  const validityText = item?.daysUntilExpiration === undefined ? "Sem data de validade" : item.daysUntilExpiration < 0 ? `Vencido há ${Math.abs(item.daysUntilExpiration)} dias` : item.daysUntilExpiration === 0 ? "Vence hoje" : `${item.daysUntilExpiration} dias restantes`;
  return <Drawer className="search-result-drawer document-details-drawer" type="overlay" position="end" size="medium" open={open} onOpenChange={(_, data) => { if (!data.open) onClose(); }}><DrawerHeader><DrawerHeaderTitle action={<Button appearance="subtle" aria-label="Fechar detalhes" icon={<Dismiss24Regular />} onClick={onClose} />}>Detalhes do documento</DrawerHeaderTitle></DrawerHeader><DrawerBody>{item && record ? <div className="drawer-record document-details"><div className="drawer-record__identity"><span className="registration-type-label">Documento rural</span><h2>{item.type}</h2><p>{item.number || "Sem número informado"}</p><StatusBadge status={documentValidityLabels[item.validityStatus]} /></div>
    <section className="drawer-record__section"><h3>Identificação</h3><dl className="drawer-record__details"><div><dt>Tipo</dt><dd>{item.type}</dd></div><div><dt>Número</dt><dd>{item.number || "—"}</dd></div><div><dt>Exercício</dt><dd>{item.exercise || "—"}</dd></div><div><dt>Situação cadastral</dt><dd>{item.status === "active" ? "Ativo" : "Inativo"}</dd></div></dl></section>
    <section className={`document-validity-card document-validity-card--${item.validityStatus}`}><span><strong>Validade temporal</strong><small>Calculada em 21/08/2026</small></span><span><StatusBadge status={documentValidityLabels[item.validityStatus]} /><b>{validityText}</b></span><dl><div><dt>Emissão</dt><dd>{date(item.issueDate)}</dd></div><div><dt>Validade</dt><dd>{date(item.expirationDate)}</dd></div></dl></section>
    <section className="drawer-record__section"><h3>Imóvel vinculado</h3><div className="document-relation-card"><span><strong>{record.farm?.name ?? "Fazenda não encontrada"}</strong><small>{record.farm ? `${record.farm.municipality} / ${record.farm.state} · ${formatArea(record.farm.totalArea)}` : "—"}</small></span><Badge appearance="tint" color="success">Fazenda</Badge></div><div className="document-relation-card"><span><strong>{record.registration ? `Matrícula ${record.registration.number}` : "Sem matrícula vinculada"}</strong><small>{record.registration ? "Vínculo registral deste documento" : "Documento relacionado somente à fazenda"}</small></span><Badge appearance="tint" color="subtle">Matrícula</Badge></div></section>
    {(item.purpose || item.licensedArea !== undefined || item.cab || item.sigamStatus || item.notes) ? <section className="drawer-record__section"><h3>Informações complementares</h3><dl className="drawer-record__details"><div><dt>Finalidade</dt><dd>{item.purpose || "—"}</dd></div><div><dt>Área licenciada</dt><dd>{item.licensedArea === undefined ? "—" : formatArea(item.licensedArea)}</dd></div><div><dt>CAB</dt><dd>{item.cab || "—"}</dd></div><div><dt>Situação SIGAM</dt><dd>{item.sigamStatus || "—"}</dd></div><div className="document-details__wide"><dt>Observações</dt><dd>{item.notes || "—"}</dd></div></dl></section> : null}
    <section className="drawer-record__section document-attachments"><div className="document-section-heading"><div><h3>Arquivos vinculados</h3><span>{record.attachments.length} referência{record.attachments.length === 1 ? "" : "s"} de rede</span></div><Button appearance="primary" size="small" icon={<Add20Regular />} onClick={onAddAttachment}>Adicionar referência</Button></div>{record.attachments.length ? <div className="document-attachment-list">{record.attachments.map((attachment) => <div key={attachment.id}><span><strong>{attachment.fileName}</strong><small>{attachment.filePath}</small><em>{attachment.fileType || "Arquivo"} · {size(attachment.fileSize)}</em></span><Menu positioning="below-end"><MenuTrigger disableButtonEnhancement><Button appearance="subtle" size="small" icon={<MoreHorizontal20Regular />} aria-label={`Ações para ${attachment.fileName}`} /></MenuTrigger><MenuPopover><MenuList><MenuItem icon={<Edit20Regular />} onClick={() => onEditAttachment(attachment)}>Editar referência</MenuItem><MenuItem icon={<Copy20Regular />} onClick={() => onCopyPath(attachment)}>Copiar caminho</MenuItem><MenuItem className="registration-menu-danger" icon={<Delete20Regular />} onClick={() => onRemoveAttachment(attachment)}>Remover referência</MenuItem></MenuList></MenuPopover></Menu></div>)}</div> : <p className="registration-drawer__empty">Nenhuma referência de arquivo vinculada.</p>}</section>
    <section className="drawer-record__section"><h3>Auditoria</h3><dl className="drawer-record__details"><div><dt>Cadastrado em</dt><dd>{date(item.createdAt)}</dd></div><div><dt>Atualizado em</dt><dd>{date(item.updatedAt)}</dd></div></dl></section>
  </div> : null}</DrawerBody><DrawerFooter><Button appearance="primary" icon={<Edit20Regular />} disabled={!item} onClick={onEdit}>Editar documento</Button><Button appearance="secondary" onClick={onClose}>Fechar</Button></DrawerFooter></Drawer>;
}
