import { useMemo } from "react";
import { Button, DataGrid, DataGridBody, DataGridCell, DataGridHeader, DataGridHeaderCell, DataGridRow, Menu, MenuItem, MenuList, MenuPopover, MenuTrigger, Skeleton, SkeletonItem, Tooltip, createTableColumn } from "@fluentui/react-components";
import type { TableColumnDefinition } from "@fluentui/react-components";
import { Add20Regular, ChevronLeft20Regular, ChevronRight20Regular, Delete20Regular, Edit20Regular, Eye20Regular, MoreHorizontal20Regular, PersonProhibited20Regular, Shield24Regular } from "@fluentui/react-icons";
import type { CarListItem } from "../../types/car";
import { carStatusLabels } from "../../services/statusLabels";
import { StatusBadge } from "../StatusBadge";

interface Props { records: CarListItem[]; loading: boolean; filtered: boolean; page: number; totalPages: number; onView: (record: CarListItem) => void; onEdit: (record: CarListItem) => void; onInactivate: (record: CarListItem) => void; onDelete: (record: CarListItem) => void; onPageChange: (page: number) => void; onClear: () => void; onNew: () => void; }
const displayDate = (value: string) => value.includes("/") ? value : new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${value.slice(0, 10)}T00:00:00Z`));
const textCell = (value: string, strong = false) => <Tooltip content={value} relationship="description"><span className={`search-cell-text${strong ? " search-cell-text--strong" : ""}`}>{value}</span></Tooltip>;

export function CarGrid({ records, loading, filtered, page, totalPages, onView, onEdit, onInactivate, onDelete, onPageChange, onClear, onNew }: Props) {
  const columns: TableColumnDefinition<CarListItem>[] = useMemo(() => [
    createTableColumn({ columnId: "number", compare: (a, b) => a.number.localeCompare(b.number), renderHeaderCell: () => "Número CAR", renderCell: (item) => textCell(item.number, true) }),
    createTableColumn({ columnId: "farm", compare: (a, b) => a.farmName.localeCompare(b.farmName, "pt-BR"), renderHeaderCell: () => "Fazenda", renderCell: (item) => textCell(item.farmName) }),
    createTableColumn({ columnId: "registration", compare: (a, b) => (a.registrationNumber ?? "").localeCompare(b.registrationNumber ?? ""), renderHeaderCell: () => "Matrícula", renderCell: (item) => textCell(item.registrationNumber ?? "—") }),
    createTableColumn({ columnId: "owner", compare: (a, b) => (a.ownerName ?? "").localeCompare(b.ownerName ?? "", "pt-BR"), renderHeaderCell: () => "Proprietário", renderCell: (item) => textCell(item.ownerName ?? "—") }),
    createTableColumn({ columnId: "receipt", compare: (a, b) => (a.receiptNumber ?? "").localeCompare(b.receiptNumber ?? ""), renderHeaderCell: () => "Número do recibo", renderCell: (item) => textCell(item.receiptNumber ?? "—") }),
    createTableColumn({ columnId: "status", compare: (a, b) => a.status.localeCompare(b.status), renderHeaderCell: () => "Situação", renderCell: (item) => <StatusBadge status={carStatusLabels[item.status]} /> }),
    createTableColumn({ columnId: "updated", compare: (a, b) => a.updatedAt.localeCompare(b.updatedAt), renderHeaderCell: () => "Atualizado em", renderCell: (item) => displayDate(item.updatedAt) }),
    createTableColumn({ columnId: "actions", renderHeaderCell: () => "Ações", renderCell: (item) => <div className="document-grid__actions" onClick={(event) => event.stopPropagation()}><Button appearance="subtle" size="small" icon={<Eye20Regular />} aria-label={`Abrir ${item.number}`} onClick={() => onView(item)} /><Menu><MenuTrigger disableButtonEnhancement><Button appearance="subtle" size="small" icon={<MoreHorizontal20Regular />} aria-label={`Ações de ${item.number}`} /></MenuTrigger><MenuPopover><MenuList><MenuItem icon={<Edit20Regular />} onClick={() => onEdit(item)}>Editar</MenuItem><MenuItem icon={<PersonProhibited20Regular />} disabled={item.status === "inactive"} onClick={() => onInactivate(item)}>Inativar</MenuItem><MenuItem icon={<Delete20Regular />} onClick={() => onDelete(item)}>Excluir</MenuItem></MenuList></MenuPopover></Menu></div> }),
  ], [onDelete, onEdit, onInactivate, onView]);
  if (loading && !records.length) return <Skeleton className="document-grid__skeleton" aria-label="Carregando cadastros CAR">{Array.from({ length: 7 }, (_, index) => <SkeletonItem key={index} shape="rectangle" size={40} />)}</Skeleton>;
  if (!records.length) return <div className="document-empty-state"><span><Shield24Regular /></span><h3>{filtered ? "Nenhum CAR encontrado" : "Nenhum CAR cadastrado"}</h3><p>{filtered ? "Ajuste os filtros para encontrar outros registros." : "Cadastre o primeiro CAR do sistema."}</p><div>{filtered ? <Button onClick={onClear}>Limpar filtros</Button> : null}<Button appearance="primary" icon={<Add20Regular />} onClick={onNew}>Novo CAR</Button></div></div>;
  return <><div className="data-grid-wrap document-grid"><DataGrid items={records} columns={columns} size="small" sortable getRowId={(item) => item.id}><DataGridHeader><DataGridRow>{({ renderHeaderCell }) => <DataGridHeaderCell>{renderHeaderCell()}</DataGridHeaderCell>}</DataGridRow></DataGridHeader><DataGridBody<CarListItem>>{({ item, rowId }) => <DataGridRow<CarListItem> key={rowId} onClick={() => onView(item)}>{({ renderCell }) => <DataGridCell>{renderCell(item)}</DataGridCell>}</DataGridRow>}</DataGridBody></DataGrid></div><nav className="consulta-pagination" aria-label="Paginação do CAR"><Button appearance="subtle" size="small" icon={<ChevronLeft20Regular />} disabled={page <= 1} onClick={() => onPageChange(page - 1)}>Anterior</Button><div className="consulta-pagination__pages">{Array.from({ length: totalPages }, (_, index) => index + 1).map((number) => <Button key={number} appearance={number === page ? "primary" : "subtle"} size="small" onClick={() => onPageChange(number)}>{number}</Button>)}</div><Button appearance="subtle" size="small" iconPosition="after" icon={<ChevronRight20Regular />} disabled={page >= totalPages} onClick={() => onPageChange(page + 1)}>Próxima</Button></nav></>;
}
