import type { PostgrestError } from "@supabase/supabase-js";
import { supabase } from "../lib/supabase";
import type { CarRepository, CarRepositoryInput, PersistedCarRecord } from "./carRepository";
import { CarConcurrencyError } from "./carRepository";

interface CarRow { id: string; farm_id: string; registration_id: string | null; car_number: string; receipt_number: string | null; declared_owner_name: string | null; status: "active" | "pending" | "inactive"; notes: string | null; created_at: string; updated_at: string; version: number; }
const selection = "id, farm_id, registration_id, car_number, receipt_number, declared_owner_name, status, notes, created_at, updated_at, version";
const formatTimestamp = (value: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: "America/Araguaina" }).format(new Date(value));
const mapRow = (row: CarRow): PersistedCarRecord => ({ id: row.id, farmId: row.farm_id, registrationId: row.registration_id ?? undefined, number: row.car_number, receiptNumber: row.receipt_number ?? undefined, declaredOwnerName: row.declared_owner_name ?? undefined, status: row.status, notes: row.notes ?? undefined, createdAt: formatTimestamp(row.created_at), updatedAt: formatTimestamp(row.updated_at), version: row.version });
const mapInput = (input: CarRepositoryInput) => ({ farm_id: input.farmId, registration_id: input.registrationId ?? null, car_number: input.carNumber, receipt_number: input.receiptNumber || null, declared_owner_name: input.declaredOwnerName || null, status: input.status, notes: input.notes || null });
const friendlyError = (error: PostgrestError, fallback: string) => { if (error.code === "23505") return new Error("Já existe um CAR com este número."); if (error.code === "23503") return new Error("A Matrícula selecionada não pertence à Fazenda informada."); if (error.code === "42501") return new Error("Você não possui permissão para realizar esta ação."); if (error.code === "40001") return new CarConcurrencyError(); return new Error(fallback); };
const currentOrganizationId = async () => { const { data: authData } = await supabase.auth.getUser(); if (!authData.user) throw new Error("Sua sessão não pôde ser validada. Entre novamente."); const { data, error } = await supabase.from("profiles").select("organization_id").eq("id", authData.user.id).eq("status", "active").maybeSingle(); if (error || !data?.organization_id) throw new Error("Seu usuário não possui um perfil ativo para acessar o sistema."); return data.organization_id as string; };
const queryList = async (column?: "farm_id" | "registration_id", id?: string) => { let query = supabase.from("car_records").select(selection).is("deleted_at", null).order("updated_at", { ascending: false }); if (column && id) query = query.eq(column, id); const { data, error } = await query; if (error) throw friendlyError(error, "Não foi possível carregar os cadastros CAR."); return ((data ?? []) as unknown as CarRow[]).map(mapRow); };
export const supabaseCarRepository: CarRepository = {
  list: () => queryList(), listByFarm: (id) => queryList("farm_id", id), listByRegistration: (id) => queryList("registration_id", id),
  async getById(id) { const { data, error } = await supabase.from("car_records").select(selection).eq("id", id).is("deleted_at", null).maybeSingle(); if (error) throw friendlyError(error, "Não foi possível carregar o CAR."); return data ? mapRow(data as unknown as CarRow) : undefined; },
  async create(input) { const organizationId = await currentOrganizationId(); const { data, error } = await supabase.from("car_records").insert({ organization_id: organizationId, ...mapInput(input) }).select(selection).single(); if (error) throw friendlyError(error, "Não foi possível cadastrar o CAR."); return mapRow(data as unknown as CarRow); },
  async update(id, expectedVersion, input) { const { data, error } = await supabase.from("car_records").update(mapInput(input)).eq("id", id).eq("version", expectedVersion).is("deleted_at", null).select(selection).maybeSingle(); if (error) throw friendlyError(error, "Não foi possível atualizar o CAR."); if (!data) throw new CarConcurrencyError(); return mapRow(data as unknown as CarRow); },
  async inactivate(id, expectedVersion) { const current = await this.getById(id); if (!current) throw new CarConcurrencyError(); return this.update(id, expectedVersion, { farmId: current.farmId, registrationId: current.registrationId, carNumber: current.number, receiptNumber: current.receiptNumber, declaredOwnerName: current.declaredOwnerName, status: "inactive", notes: current.notes }); },
  async softDelete(id, expectedVersion) { const { data, error } = await supabase.rpc("soft_delete_record", { p_entity_type: "car_records", p_id: id, p_expected_version: expectedVersion }); if (error) throw friendlyError(error, "Não foi possível excluir o CAR."); if (data !== 1) throw new CarConcurrencyError(); },
};
