import { Badge, Button, Drawer, DrawerBody, DrawerFooter, DrawerHeader, DrawerHeaderTitle, Menu, MenuItem, MenuList, MenuPopover, MenuTrigger } from "@fluentui/react-components";
import { Add20Regular, Delete20Regular, Dismiss24Regular, Edit20Regular, MoreHorizontal20Regular, Open20Regular, PersonProhibited20Regular } from "@fluentui/react-icons";
import { formatArea, formatCurrency, formatIsoDate } from "../../services/searchUtils";
import type { RegistrationDetailsViewModel, RegistrationOwnershipView } from "../../types/matricula";
import { StatusBadge } from "../StatusBadge";
import { getDocumentValidityStatus } from "../../data/mock/selectors";

interface RegistrationDetailsDrawerProps {
  record?: RegistrationDetailsViewModel; open: boolean; onClose: () => void; onEdit: () => void; onAddOwner: () => void; onEditOwner: (value: RegistrationOwnershipView) => void; onCloseOwner: (value: RegistrationOwnershipView) => void; onDeleteOwner: (value: RegistrationOwnershipView) => void; onSeeAllOperations: () => void;
}
const linkLabels = { owner: "Proprietário", "co-owner": "Coproprietário", usufructuary: "Usufrutuário", other: "Outro" } as const;
const operationStatus = { under_review: "Em análise", active: "Ativa", completed: "Concluída", cancelled: "Cancelada" } as const;
const guaranteeStatus = { active: "Ativa", closed: "Encerrada", cancelled: "Cancelada" } as const;
const documentStatus = { active: "Ativo", expiring: "A vencer", expired: "Vencido", inactive: "Inativo" } as const;
const displayDate = (value?: string) => value ? value.includes("/") ? value : formatIsoDate(value) : "—";
const formatPercentage = (value?: number) => value === undefined ? "Não informado" : `${new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(value)}%`;

export function RegistrationDetailsDrawer({ record, open, onClose, onEdit, onAddOwner, onEditOwner, onCloseOwner, onDeleteOwner, onSeeAllOperations }: RegistrationDetailsDrawerProps) {
  const registration = record?.registration;
  return <Drawer className="search-result-drawer registration-drawer" type="overlay" position="end" size="medium" open={open} onOpenChange={(_, data) => { if (!data.open) onClose(); }}><DrawerHeader><DrawerHeaderTitle action={<Button appearance="subtle" aria-label="Fechar detalhes" icon={<Dismiss24Regular />} onClick={onClose} />}>{registration ? `Matrícula ${registration.number}` : "Detalhes da matrícula"}</DrawerHeaderTitle></DrawerHeader><DrawerBody>{registration && record ? <div className="drawer-record registration-details">
    <div className="drawer-record__identity"><span className="registration-type-label">Registro imobiliário rural</span><h2>Matrícula {registration.number}</h2><p>{registration.farmName}</p><StatusBadge status={registration.status === "active" ? "Ativa" : "Inativa"} /></div>
    <section className="drawer-record__section"><h3>Informações registrais</h3><dl className="drawer-record__details"><div><dt>Número</dt><dd>{registration.number}</dd></div><div><dt>Matrícula anterior</dt><dd>{registration.previousNumber || "—"}</dd></div><div><dt>Área legal</dt><dd>{registration.legalArea === undefined ? "—" : formatArea(registration.legalArea)}</dd></div><div><dt>HP</dt><dd>{registration.hp || "—"}</dd></div><div><dt>Data da certidão</dt><dd>{displayDate(registration.certificateDate)}</dd></div><div><dt>Fazenda</dt><dd>{registration.farmName}</dd></div></dl></section>
    <section className="drawer-record__section"><h3>Imóvel vinculado</h3>{record.farm ? <div className="registration-farm-card"><span><strong>{record.farm.name}</strong><small>{record.farm.municipality} / {record.farm.state} · {formatArea(record.farm.totalArea)}</small></span><StatusBadge status={record.farm.status === "active" ? "Ativa" : "Inativa"} /></div> : <p className="registration-drawer__empty">Fazenda não encontrada.</p>}</section>
    <section className="drawer-record__section"><div className="registration-section-heading"><div><h3>Proprietários e vínculos</h3><span>Percentual ativo vinculado <strong>{formatPercentage(record.activePercentage)}</strong></span></div><Button appearance="primary" size="small" icon={<Add20Regular />} disabled={registration.status === "inactive"} onClick={onAddOwner}>Vincular proprietário</Button></div>{record.activePercentage < 100 ? <Badge appearance="tint" color="warning" className="registration-percentage-badge">{formatPercentage(record.activePercentage)} informado</Badge> : null}<div className="registration-ownership-list">{record.ownerships.length ? record.ownerships.map((item) => <div key={item.link.id}><span><strong>{item.owner.name}</strong><small>{item.owner.document} · {linkLabels[item.link.type]} · {formatPercentage(item.link.percentage)}</small></span><div className="registration-ownership-list__actions"><StatusBadge status={item.link.status === "active" ? "Ativo" : "Inativo"} /><Menu positioning="below-end"><MenuTrigger disableButtonEnhancement><Button appearance="subtle" size="small" icon={<MoreHorizontal20Regular />} aria-label={`Ações do vínculo de ${item.owner.name}`} /></MenuTrigger><MenuPopover><MenuList><MenuItem icon={<Edit20Regular />} onClick={() => onEditOwner(item)}>Editar vínculo</MenuItem><MenuItem icon={<PersonProhibited20Regular />} disabled={item.link.status === "inactive"} onClick={() => onCloseOwner(item)}>Encerrar vínculo</MenuItem><MenuItem className="registration-menu-danger" icon={<Delete20Regular />} onClick={() => onDeleteOwner(item)}>Excluir vínculo</MenuItem></MenuList></MenuPopover></Menu></div></div>) : <p className="registration-drawer__empty">Nenhum proprietário vinculado.</p>}</div></section>
    <section className="drawer-record__section"><div className="registration-related-heading"><h3>Operações</h3>{record.operations.length > 3 ? <Button appearance="subtle" size="small" icon={<Open20Regular />} onClick={onSeeAllOperations}>Ver todas</Button> : null}</div>{record.operations.length ? <div className="registration-detail-list">{record.operations.slice(0, 3).map((operation) => <div key={operation.id}><span><strong>{operation.number}</strong><small>{operation.bank} · {formatCurrency(operation.value)}</small></span><StatusBadge status={operationStatus[operation.status]} /></div>)}</div> : <p className="registration-drawer__empty">Nenhuma operação relacionada.</p>}</section>
    <section className="drawer-record__section"><h3>Garantias</h3>{record.guarantees.length ? <div className="registration-detail-list">{record.guarantees.map((guarantee) => { const operation = record.operations.find((item) => item.id === guarantee.operationId); return <div key={guarantee.id}><span><strong>{guarantee.type}</strong><small>{operation?.number ?? "Operação não encontrada"} · {formatCurrency(guarantee.value ?? 0)}</small></span><StatusBadge status={guaranteeStatus[guarantee.status]} /></div>; })}</div> : <p className="registration-drawer__empty">Nenhuma garantia relacionada.</p>}</section>
    <section className="drawer-record__section"><h3>Documentos relacionados</h3>{record.documents.length ? <div className="registration-detail-list">{record.documents.map((document) => <div key={document.id}><span><strong>{document.type}</strong><small>{document.issueDate ? `Emissão ${displayDate(document.issueDate)}` : document.expirationDate ? `Vencimento ${displayDate(document.expirationDate)}` : document.number || "Sem data informada"}</small></span><StatusBadge status={documentStatus[getDocumentValidityStatus(document)]} /></div>)}</div> : <p className="registration-drawer__empty">Nenhum documento relacionado.</p>}</section>
    <section className="drawer-record__section"><h3>Auditoria</h3><dl className="drawer-record__details"><div><dt>Cadastrada em</dt><dd>{registration.createdAt}</dd></div><div><dt>Atualizada em</dt><dd>{registration.updatedAt}</dd></div></dl></section>
  </div> : null}</DrawerBody><DrawerFooter><Button appearance="primary" icon={<Edit20Regular />} disabled={!registration} onClick={onEdit}>Editar</Button><Button appearance="secondary" onClick={onClose}>Fechar</Button></DrawerFooter></Drawer>;
}

